# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Performance', '~> 5.15.0'

target 'nightguideApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nightguideApp

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  'RCTImage' # Needed for FlatImage
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # 3rd party podspecs
  
  # FB SDK
  pod 'FBSDKCoreKit', '4.42.0'
  pod 'FBSDKShareKit', '4.42.0'
  pod 'FBSDKLoginKit', '4.42.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  
  target 'nightguideAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  # https://github.com/facebook/react-native/issues/20492#issuecomment-422958184
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      
      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"
      
      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
      
    end
  end

end
