# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Performance', '~> 5.15.0'

target 'nightguideApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nightguideApp

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'FBSDKCoreKit', '4.42.0'
  pod 'FBSDKShareKit', '4.42.0'
  pod 'FBSDKLoginKit', '4.42.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'nightguideAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
